---
sudo: false
language: c
matrix:
  include:
    - env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=make
      language: c
      script: ./tests/make.sh

    - env: TEST=terraform
      language: c
      script: |
       set -e
       cd tf
       make test

    - env: TEST=hadolint
      language: c
      services:
        - docker
      script: ./tests/hadolint.sh

    - env: TEST=yamllint
      language: c
      services:
        - docker
      script: ./tests/yamllint.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
