---
sudo: false
language: c
matrix:
  include:
    - env: TEST=markdownlint
      language: c
      services:
        - docker
      script: ./tests/mdl.sh

    - env: TEST=terraform
      services:
        - docker
      script: cd tf; ../tests/terraform.sh

    - env: TEST=yamllint
      services:
        - docker
      script: ./tests/yamllint.sh

    - env: TEST=shellcheck
      services:
        - docker
      script: ./tests/shellcheck.sh

    - env: TEST=hadolint
      language: c
      services:
        - docker
      script: ./tests/hadolint.sh

    - env: TEST=make
      language: c
      script: ./tests/make.sh
branches:
  only:
    - master
    # also matched against tag pushes
    - /^\d+\.\d+\.\d+$/
notifications:
  email: false
