# LoadBalancer service for nginx-ssl-proxy
#
# From https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/service_ssl_proxy.yaml
# See license/kube_jenkins_imager_license.txt

kind: Service
apiVersion: v1
metadata:
  name: &name nginx-ssl-proxy
  labels: &labels
    name: *name
    role: ssl-proxy
    app: eups
spec:
  selector: *labels
  type: LoadBalancer
  ports:
  - name: https
    port: 443
    targetPort: ssl-proxy-https
    protocol: TCP
  - name: http
    port: 80
    targetPort: ssl-proxy-http
    protocol: TCP
