# Replication control to run nginx-ssl-proxy
#
# From https://github.com/GoogleCloudPlatform/kube-jenkins-imager/blob/master/ssl_proxy.yaml
# See license/kube_jenkins_imager_license.txt

kind: ReplicationController
apiVersion: v1
metadata:
  name: &name nginx-ssl-proxy
  labels: &labels
    name: *name
    role: ssl-proxy
    app: eups
spec:
  replicas: 1
  selector: *labels
  template:
    metadata:
      name: *name
      labels: *labels
    spec:
      containers:
      - name: *name
        image: "docker.io/lsstsqre/nginx-ssl-proxy:latest"
        env:
          # see:
          # https://github.com/GoogleCloudPlatform/nginx-ssl-proxy/blob/master/start.sh
          - name: SERVICE_HOST_ENV_NAME
            value: EUPS_SERVICE_HOST
          - name: SERVICE_PORT_ENV_NAME
            value: EUPS_SERVICE_PORT_HTTP
          - name: ENABLE_SSL
            value: 'true'
          - name: ENABLE_BASIC_AUTH
            value: 'false'
        ports:
          # nginx-ssl-proxy takes traffic on both http and https
          # See ssl-proxy-service
          - name: ssl-proxy-http
            containerPort: 80
          - name: ssl-proxy-https
            containerPort: 443
        volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: ssl-proxy-secret
